### ISSUE TITLE
Problem with property 'apply' 

### ISSUE THREAD

**Issue by alejokum** [leftstick/angular-sweetalert#8] opened 2016-05-04 14:47 UTC
Hi, i have an issue with your amazing plugin, sometimes when open my project or realize any modification in this , the plugin throws me the following error: 
**TypeError: Cannot read property 'apply' of undefined at show (ngSweetAlert.js:32)**. 
You have any idea why this happens? in my controller i am not using 'apply', simply instantiate the modal follow as:  **sweet.show('Simple right?');**....

**Comment by leftstick** [comment] 2016-05-04 15:03
angular-sweetalert is an angular directive wrapper for sweetAlert which provide the cool modal dialog.

The issue u mentioned seems u haven't make sure angular-sweetalert is loaded after sweetAlert. But it's required.

Maybe u can provide more info, like how u reproduce this issue?

**Comment by vukan71** [comment] 2016-05-20 11:58
I have same error 

angular.js:12783 TypeError: **Cannot read property 'apply' of undefined**

It worked nice for last 5-6 months, and now suddenly I have this error.

**Comment by leftstick** [comment] 2016-05-20 12:36
@vukan71  since i haven't touch this project for at least 4 months. So the issue might not caused by the plugin.

Can you provide more info of how you use it? Especially the import part, whether inject it with `script` tag directly, or using `browserify`/ `webpack` have a bundle file. I need to know the usage

**Comment by leftstick** [comment] 2017-01-30 10:25
No further information, i am going to close it

**Closed as completed by leftstick** 2017-01-30 10:25 UTC
